# Generated by Django 5.0 on 2024-06-08 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
