# Generated by Django 5.0 on 2024-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_cart_order_orderitem_cartitem_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
